### ISSUE TITLE
Split Test.QuickCheck.Instances into multiple modules

### ISSUE THREAD

**Issue by dfithian** [phadej/qc-instances#15]
@phadej 

Would be interested in splitting out Test.QuickCheck.Instances into Test.QuickCheck.Instances.Time, Test.QuickCheck.Instances.Text, etc (and importing them into Test.QuickCheck.Instances for backwards compatibility). The reason for this is that if you want, you can define your own alternative instance (for something like Text) without losing use of the rest of the library. If you're okay with this I'll file a PR doing it. Let me know what you think.

**Comment by phadej** [comment]
I'm not against. It will be cleaner if instances were split by package.

I warn about the motivation though. `quickcheck-instances` is depended upon a lot, and it might be that instances will accidentally "leak" into your test code anyway.

**Comment by dfithian** [comment]
That's a good point, can also force using explicit generators by defining `instance Arbitrary Text where arbitrary = error "can't do that"` so that I'll get overlapping instances if I ever try to use an imported `Arbitrary Text` instance.

**Comment by phadej** [comment]
@dfithian Do you need a release asap. I'd liek to wait until GHC-8.4 will get a beta release, as then I'll go through packages I maintain anyway.

**Comment by dfithian** [comment]
I was hoping for one, but if it's too big of a deal I can always just
change the stack hash. When is the beta release supposed to be out?

**Comment by phadej** [comment]
I hope that this month
