### ISSUE TITLE
Stackage release?

### ISSUE THREAD

**Issue by MichaelXavier** [phadej/qc-instances#25]
Curious if you're open to a stackage release. I'm using this package and stackage can't run tests against my package without this. I'd be willing to pitch in if that would persuade you.

**Comment by phadej** [comment]
Aren't quickcheck-instances in both latest LTS and nightly? Am I missing something?

**Comment by MichaelXavier** [comment]
Oh jeeze this is embarrassing. I think I got this mixed up with another library that was blocking me. Sorry!

**Comment by phadej** [comment]
No worries
