### ISSUE TITLE
Bump version bound again

### ISSUE THREAD

**Issue by nick8325** [phadej/qc-instances#34]
QC 2.13 will be out soon with no new instances.

**Comment by phadej** [comment]
I’d do some changes because of change to splitmix, incl different bytestring generator. If you mind saying which QC commit will luckily to become 2.13 release, I can prepare the changes so we can make releases ~simultaneosly

**Comment by nick8325** [comment]
It's likely to be the current HEAD: https://github.com/nick8325/quickcheck/commit/82d495a05f6c12a06c7b41734f7052e8dad9f9d1
