### ISSUE TITLE
Arbitrary instances for `uuid`

### ISSUE THREAD

**Issue by hvr** [phadej/qc-instances#4]
A frequently requested feature are `Arbitrary` UUID instances, see e.g.  https://github.com/hvr/uuid/issues/27 and https://github.com/hvr/uuid/pull/29.

Does `uuid-types` qualify for `qc-instances`?

**Comment by phadej** [comment]
`uuid-types` isn't part of Hasksell Platform, but I'm not against adding `UUID` to the package. I have `Arbitrary UUID` in our company code as well.

Have to think how to reformulate

> The goal is to supply QuickCheck instances for types provided by the Haskell Platform.

to include `uuid` like packages. Ideas?

---

Happy to accept PR, btw.

**Comment by phadej** [comment]
Released in https://hackage.haskell.org/package/quickcheck-instances-0.3.14
