### ISSUE TITLE
TimeZone instance to use actual Time Zones

### ISSUE THREAD

**Issue by athanclark** [phadej/qc-instances#46]
I think the `Arbitrary` instance for `TimeZone` shouldn't be handled without precision. The current implementation just [generates random abbreviations and times](http://hackage.haskell.org/package/quickcheck-instances-0.3.22/docs/src/Test.QuickCheck.Instances.Time.html#line-79), but could use an actual list of all the _real_ time zones used in practice - like in [this Wikipedia article](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations).

I'll set up a PR to get this rolling if you agree it's a good idea.

**Comment by phadej** [comment]
real time zones don't expose what weird thing people (politicians) may come up with.

I'll be fine with 50/50 split i.e. half generating legit current existing time zones, and half still generating arbitrary "garbage".

**Comment by athanclark** [comment]
Aye aye. if it's the case that we should expect anything, then I think your implementation would be better.
